"""add workflow config

Revision ID: 9977adbfe38e
Revises: 9f1783d4f1dd
Create Date: 2026-07-15 09:43:13.052355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9977adbfe38e'
down_revision: Union[str, Sequence[str], None] = '9f1783d4f1dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'config')
    # ### end Alembic commands ###
